### ISSUE TITLE
Server is Crashing on Android - React Native Expo App

### ISSUE THREAD

**Issue by jyotipixolo** [birdofpreyru/react-native-static-server#26]
The plugin is working fin on IOS. But server is getting crashed on Android after sometime.

**Comment by birdofpreyru** [comment]
Hi @jyotipixolo , I think you might be doing it wrong: with `stopInBackground: true` the server will automatically stop when the app goes into background (and it will make its state `INACTIVE`), and then it will automatically re-start when the app is in the foreground again. The check `if (server.state === STATES.INACTIVE) {` in such scenario still may evaluate `true`, and thus trigger `.start()` once again, causing the crash.

As a rapid test, can you try adding `server.stop()` call just before `server.start()`? For server in `INACTIVE` state it will ensure no automatic re-start will happen until the `.start()` is explicitly called. If that does not solve the issue, then there is some bug to fix in the library, otherwise I'd say your code around the server should be refactored.

**Comment by jyotipixolo** [comment]
Hi @birdofpreyru, I tried stopping the server before starting it. To make things easier I took out all of my other code regarding the data and now I am just starting(After stopping) the server when I land on the screen and stopping when I exit. 

```

        // Function to check if the server is active or not and create a new one if not
	const checkAndCreateServer = async () => {
		// Get the active server - get the running server
		let server = getActiveServer();
		if (!server) {
			// If no server is active, create a new one
			server = new Server({
				fileDir: RNFS.DocumentDirectoryPath + "/scorm-player",
				nonLocal: true,
			});
		}
		if (server) {
			await server.stop();
			server.start().then((url) => {
				console.log("Server started at: ", url);
				setLocalHostURI(url);
			});
		}
	};
```
```
           useEffect(() => {
		    checkAndCreateServer();
	    }, []);
```

```
        const backAction = async () => {
		// Stop the server
		const server = getActiveServer();
		if (server && server.state === STATES.ACTIVE) {
		      await  server.stop();
		}
		navigation.goBack();
	};

```

But my server still crashes. And the crash happens at random moments, sometimes on server start and sometimes on server stop.
Most of the times the server starts successfully the first time but causes issues when I go back from the screen and return to it.

Could this be a memory issue in android ?
Is there a better way to handle the stopping of the server?

**Comment by birdofpreyru** [comment]
Agh... you know, [getActiveServer()](https://github.com/birdofpreyru/react-native-static-server/blob/469a5bccbdeb8ad591b57ab739fed1c5096dd65e/src/index.tsx#L496-L501) only returns a server, if any, when it is non-`INACTIVE`, and non-`CRASHED`. Doing what you doing, I guess, you are leaking some created server instances because they were `INACTIVE` when you call `getActiveServer()`, and attempting to create and start new server instances you eventually crash the app.

You should do at least as in [the example app](https://github.com/birdofpreyru/react-native-static-server/blob/469a5bccbdeb8ad591b57ab739fed1c5096dd65e/example/src/App.tsx#L46-L110), where the hook just keeps server reference and stops it on unmount, _i.e._ (over-simplifying the example):
```jsx
useEffect(() => {
  const server = new Server(..);
  ...
  server.start(..).then(..);
  return () => {
    server.stop();
  };
}, []);
```
this way you don't leak references to the server instances you create, and ensure that every server is correctly shutdown when the hook unmounts. Note, even with such pattern, the example does it in the root app component, thus it is sure the hook never executed more than once a time in the app (in contrast to if you put it into some component, which can be mounted and unmounted). If you do it in some component, probably `getActiveServer()` is not enough to synchronize operation of multiple server instances... although I added it into lib, I haven't gave it too much thought, as in my projects I always rely on a single server instance in the root of the app, like in the example.

**Comment by ZakiPathan2010** [comment]
I also got the same issue. I have expo bare workflow project.
What I already try till now:
1) Stop the server when screen closed
2) Wait until server is stop with then & catch block. In then block I do navigation.goBack()
3) Never stop the server 
4) Check if any active server is there if not then only create & start a new server
5) Stop previous server before starting a new one

Nothing works. App is freezing randomly on different points. & without server code everything is working fine.

I am attaching one simple project with server code with 2 screens in it, just starting & stopping the server in different ways. You can check it here : https://we.tl/t-dZ1nq3dmQk

**Comment by birdofpreyru** [comment]
@ZakiPathan2010 please, re-read my previous comment. I see in your giant archive the same code fragment I commented about above, which potentially creates multiple server instances when the screen mounts/unmounts, because there is no syncrhonization between different screen instances, I guess; also it does not stop the server when screen is unmounted &mdash; I don't know what are you trying to do, but probably you'll do better if you just create a single server instance at the root of the app, and stop it when you are sure you don't need it.

**Comment by jyotipixolo** [comment]
One more thing that needs to be considered is that my code is working absolutely fine in the **IOS simulator** and on a real device. But the server is crashing on Android.

**Comment by birdofpreyru** [comment]
Well, on Android I use it in several app distributed via Google.Play, and installed on ~5k devices in total. All set up to report me errors and crashes via Sentry. So far I haven't seen the servers crashing there. Maybe I miss something; maybe your code works fine in ios and simulator because they implement the execution flow sync between js and native differently and it prevents potential issues with your code i pointed above. 

I'll be on the lookout for crashes on Android, but so far haven't seen them myself, but I also use it the way demoed in the example app.

**Comment by jyotipixolo** [comment]
I tried clearing all the server instances before I start a new server. I made a function that returned an array of all the servers (in any state they are in). This always returned an empty array, only then I started a new server. But the freezing still exists. The server crash happens inside the "launch" function in the server.java file. Because any log after that is not seen. I also put the start server code inside a useEffect in my app.tsx too, with a plan that I start the server initially and keep it that way till I need it in my inner page. But I don't even get past my Login Screen and the server crashes and the app freezes. Is these a version of the plugin that is more suited for Android?

**Comment by jyotipixolo** [comment]
I'm just trying to make it work now. So this is what I'm doing in my App.tsx. I tried to replicate the example code. I have taken out any restart code, or any references to the plugin on any other components.

The starts normally like always.

My App.tsx has a stack of screens, the initial one being the Login Screen. While I'm still on the Login Screen the server crashes.

`useEffect(() => {
      let server: null | Server = new Server({
            fileDir: RNFS.DocumentDirectoryPath + "/scorm-player",
		stopInBackground: true,
	});
	(async () => {
		server?.addStateListener((newState) => {
			console.log(`New server state is "${STATES[newState]}"`);
		});
		const res = await server?.start();
		if (res && server) {
			console.log(`Server is running at ${res}`);
		}
	})();
	return () => {
		(async () => {
			server?.stop();
			server = null;
		})();
	};
}, []);`
	

These are the Logs I feel would be relevant.

`**lighttpd**  - E - (../../../../../lighttpd1.4/src/server.c.1057) [note] graceful shutdown started
**lighttpd** - E - (../../../../../lighttpd1.4/src/server.c.2082) server stopped by UID = 10716 PID = 6606
**RN_STATIC_SERVER** - I -  Res -1
**RN_STATIC_SERVER**  - E -  Server crashed
java.lang.Exception: Native server exited with status -1 at com.lighttpd.Server.run(Server.java:82)`

The above logs were formed without server.stop() being called.


I noticed another log, way before the crash happened.
`**ReactNativeJNI**  - I -  Memory warning (pressure level: TRIM_MEMORY_RUNNING_CRITICAL) received by JS VM, running a GC`
But again, when I'm not starting the server, the freezing issue stops.


Do you think there are any other packages in my code that might be clashing with yours?

**Comment by birdofpreyru** [comment]
Well... are you sure there is nothing else in your app consuming too much memory, and thus triggering OS to garbage-collect / kill stuff?

> **ReactNativeJNI**  - I -  Memory warning (pressure level: TRIM_MEMORY_RUNNING_CRITICAL) received by JS VM, running a GC

:point_up: This reads like, yeah, too much memory consumed, OS started to fight for resources.

> **lighttpd**  - E - (../../../../../lighttpd1.4/src/server.c.1057) [note] graceful shutdown started
> **lighttpd** - E - (../../../../../lighttpd1.4/src/server.c.2082) server stopped by UID = 10716 PID = 6606

:point_up: These actually come from Lighttpd core. Should be looked up there, but the way they read... looks like the server attempted and completed a graceful shutdown, the same like when `.stop()` is called. If you haven't asked for it, neither app transition to background, alongside with `stopInBackground` flag caused it... I believe Lighttpd listen for OS interrupts, I guess if Android runs out of memory, and sends some interrupts to app processes asking them to quit, if possible, to reclaim some memory, probably that can trigger server's graceful shutdown and exit with non-zero status code &mdash; this all should be checked, I am just saying out of my head, not really knowing this stuff in details.

> **RN_STATIC_SERVER** - I -  Res -1 **RN_STATIC_SERVER**  - E -  Server crashed java.lang.Exception: Native server exited with status -1 at com.lighttpd.Server.run(Server.java:82)

:point_up: And this comes from Java layer of this library, specifically from [this point](https://github.com/birdofpreyru/react-native-static-server/blob/b8cebc1c6e0fd6c241b6c6bcdba043cfcacaa743/android/src/main/java/com/lighttpd/Server.java#L80). As you see, there is a trivial logic behind it &mdash; if process exited with non-zero status &mdash; throw exception, say it crashed.

So, if you wanna look into this further yourself, I guess the next thing is to look into Lighttpd sources, [this file specifically](https://github.com/birdofpreyru/lighttpd1.4/blob/master/src/server.c), and try to figure out what can cause it to attempt a graceful shutdown and exit with -1 status.

**Comment by ZakiPathan2010** [comment]
Hi @birdofpreyru , so here is what I’m trying to do in my sample project. This project has nothing else to make sure there is no memory leak from anywhere else. I started the server in app.tsx file (just like in the example code) which is the entry point of my app & I have two screens which navigates to each other without any server code. There is no reference to the server anywhere else in the code except the App.tsx. So what happens here, is that my server is starts as usual & when I navigate from 1st screen to 2nd screen & go back to 1st screen, after a few times the app freezes. In this process the app is not in background & I never closed it.

I’m my main app too, after starting the server I would have to navigate to other screens as I did in my last example.

I am attaching my project here so you can try it by yourself too. [Sample Project](https://we.tl/t-hXLVyVH85S)
Also things to note are: my project is a expo ejected bare React project.

**Comment by jyotipixolo** [comment]
Usage in React Native:
**Lighttpd**: Not typically used within React Native projects due to its complexity and the fact that it’s designed more for server environments.
**NanoHttpd**: Commonly used in React Native, particularly for serving local files within the application. This is because it can be easily embedded and runs efficiently within the Android environment.



That's why our server was getting killed and it was crashing.

**Comment by birdofpreyru** [comment]
> _Usage in React Native: ..._

Tells who? Some kind of Artificial Idiocy?

> _NanoHttpd: Commonly used in React Native, particularly for serving local files within the application. This is because it can be easily embedded and runs efficiently within the Android environment._

1. HanoHttpd was a Java-only server; and React Native is at least Android, iOS, macOS, Windows.
2. The last release of NanoHttpd was 8 years ago, with no further development seen in their repo.

These are two main reasons why this library is powered by Lighttpd &mdash; the same, actively maintained server across all platforms.

> That's why our server was getting killed and it was crashing.

Nah... most probably it crashes because you do something wrong in your code; or there might be some bug in the library somewhere.

**Comment by gstrauss** [comment]
@jyotipixolo 
> That's why our server was getting killed and it was crashing.

Maybe I missed it, but you provided no evidence for that statement.  Just an unsubstantiated conclusion.

If you can trace the process or thread which starts lighttpd using `strace`, that may help identify what system call is failing and resulting in lighttpd shutting down.  (I don't know if this is possible in the Android debug env)

`[note] graceful shutdown started` suggests that the lighttpd thread received SIGINT (lighttpd graceful shutdown) or SIGUSR1 (lighttpd graceful restart).  If that was not intended, then maybe your app should block signals in the lighttpd thread so that signals are not delivered to the lighttpd thread, e.g. `sigprocmask()`.  That might be a good idea if the java app manages the lifetime of the lighttpd thread and you do not want/need lighttpd to react to signals.

**Comment by jyotipixolo** [comment]
Hey, @gstrauss !

When we switched to the plugin version which is based on nanohttpd, our local server stopped crashing and our app has been running for like a year now.

**Comment by steffenkleinle** [comment]
In case somebody else stumbles upon this, using an already occupied port might also lead to this crash. We got this error of the native server just crashing instantly for a different reason: We have multiple white labels of an app that all use the static server. We had a hard coded port set, so if a different white label was already active (in the background), the server on the app directly crashed. Removing the hard coded port fixed the problem for us.
We didn't experience this in the past, so perhaps something related changed at some point.
https://github.com/digitalfabrik/integreat-app/pull/4003
